CREATE DATABASE CONSULTORIO;
USE CONSULTORIO;


-- Criando as tabelas
DROP TABLE IF EXISTS MEDICO;
CREATE TABLE MEDICO(
	IDMEDICO INT,
    NOME_MEDICO VARCHAR(30) NOT NULL,
    CRM_MEDICO VARCHAR(6) UNIQUE NOT NULL,
    ESPECIALIDADE ENUM('Geral', 'Onco', 'Imuno', 'Orto', 'Endo', 'Psi', 'Neuro', 'Cardio'), 
    TELEFONE_MEDICO VARCHAR(10) NOT NULL
    );
    

DROP TABLE IF EXISTS PACIENTE;
CREATE TABLE PACIENTE(
	IDPACIENTE INT,
    NOME_PACIENTE VARCHAR(50) NOT NULL,
    SEXO ENUM('M','F') NOT NULL,
    TELEFONE_PACIENTE VARCHAR(10) NOT NULL,
    ENDERECO_PACIENTE VARCHAR(100) NOT NULL
);


SHOW TABLES;

